# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_DOTFILE_PATH = /darwin/ =~ RUBY_PLATFORM ? ".vagrant" : ".vagrant-sub"
currpath = ENV['VAGRANT_DOTFILE_PATH'] || '.vagrant'
if currpath != VAGRANT_DOTFILE_PATH
  ENV['VAGRANT_DOTFILE_PATH'] = VAGRANT_DOTFILE_PATH
  args = ARGV.join(' ')
  system "vagrant #{args}"
  FileUtils.rm_r(currpath)
  abort 'Finished'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  settings = {}
  settings[:ipaddr] = "192.168.0.33"
  settings[:port] = 2252
  settings[:workspace_path] = "~/Dropbox/workspace/profile/"

  config.vm.define "profile-dev" do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.hostname = "profile-dev"
    node.vm.network :public_network, ip: settings[:ipaddr], bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: settings[:port], id: "ssh"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.synced_folder "setup", "/vagrant",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.vm.provision :ansible_local do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = "setup.yml"
  end

  config.ssh.pty = true
end
