- name: add docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo
- name: install docker-ce
  yum: name=docker-ce state=latest
- name: add group
  user: name=vagrant groups=docker append=yes
  become: yes
- name: restart docker
  service: name=docker state=restarted
- name: install docker-compose
  pip: name=docker-compose state=latest